[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  PUBLIC_DATOCMS_API_TOKEN = "Change me for the \"GraphQL API Token\" from the DatoCMS project you just created"
  NEXT_PUBLIC_WEBHOOK_TOKEN = "Any secure random string"
  TURSO_DATABASE_URL = "Change me to your Turso database URL"
  TURSO_AUTH_TOKEN = "Change me for your Turso read/write auth token"
